# Batman Incorporated - Infinity Mode Configuration

infinity_mode:
  enabled: true
  auto_launch: true
  max_agents: 5
  coordination_interval: 5  # seconds
  
agents:
  alfred:
    capabilities: ["backend", "api", "architecture", "database", "python"]
    max_concurrent_tasks: 3
    
  robin:
    capabilities: ["devops", "automation", "ci_cd", "scripts", "deployment"]
    max_concurrent_tasks: 2
    
  oracle:
    capabilities: ["testing", "security", "quality_assurance", "validation"]
    max_concurrent_tasks: 2
    
  batgirl:
    capabilities: ["frontend", "ui", "ux", "react", "css", "accessibility"]
    max_concurrent_tasks: 3
    
  lucius:
    capabilities: ["research", "optimization", "innovation", "performance"]
    max_concurrent_tasks: 2

terminal:
  preferred: "gnome-terminal"  # gnome-terminal, wezterm, tmux
  fallback: "xterm"
  
monitoring:
  enabled: true
  update_interval: 2
  log_retention_days: 7
